### PR TITLE
feat: support .gql extension

### LINKED ISSUE #244: importSchema does not work with .gql extension
I have the exact same schema, one with the .graphql extension and the other with .gql extension.  importSchema works on the first (.graphql), but not the second 

    const { importSchema } = require('graphql-import')
    //let typeDefs = importSchema(__dirname+"/schema.graphql")
    let typeDefs = importSchema(__dirname+"/schema.gql") 
    console.log(typeDefs)

In the second case, the error thrown is

    /<DIRECTORY>/node_modules/graphql/language/lexer.js:316
      throw (0, _error.syntaxError)(source, position, unexpectedCharacterMessage(code));
      ^
    Syntax Error: Cannot parse the unexpected character "/".

This is with graphql-import 0.7.1

Thanks!

### PR DESCRIPTION
**Pull request by jedmao**
I need this for https://github.com/prisma/graphql-config/pull/124

fix #244

### CODE REVIEW

**Comment by eole1712** [comment]
any news for this guys ?

**Comment by ardatan** [comment]
Thank you @eole1712 !

**Comment by jedmao** [comment]
@ardatan, what are you thanking him for?

**Comment by ardatan** [comment]
I'm sorry @jedmao my bad

**Pull request merged**
